/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filesync.screens;

import filesync.comunicao.Request;
import filesync.persistencia.Node_info;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;

/**
 *
 * @author Reinaldo
 */
public class MainScreenServer extends javax.swing.JFrame {

    /**
     * Creates new form MainScreenServer
     */
    InetAddress ip_client;
    ServerSocket server_skt;
    Socket skt;

    ObjectInputStream input;
    ObjectOutputStream output;

    public MainScreenServer() {
        initComponents();

        try {

            server_skt = new ServerSocket(12345);
            ArrayList directory = new ArrayList();

            while (true) {

                directory.clear();

                skt = server_skt.accept();
                input = new ObjectInputStream(skt.getInputStream());

                Request req = (Request) input.readObject();

                switch (req.getType()) {
                    case "leitura":
                        File choose = new File(req.getPath().getAbsolutePath());
                        directory = preenche(choose);
                        output = new ObjectOutputStream(skt.getOutputStream());
                        output.writeObject(directory);
                        break;
                    case "download":
                        break;
                    case "upload":
                        break;
                }
            }

        } catch (IOException e) {
            System.out.println(" erro ai");
        } catch (ClassNotFoundException e2) {
            System.out.println("falha ao encontrar pasta selecionada");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public ArrayList preenche(File choose) {

        ArrayList absolute = new ArrayList();
        
        for (File arquivo : choose.listFiles()) {
            if (arquivo.isFile()) {
                absolute.add(new Node_info(arquivo.getName(), arquivo.lastModified(), null));
            } else {
                absolute.add(preenche(arquivo));
            }
        }

        return absolute;

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
